### ISSUE TITLE
`atom.toPromise()` is always pending

### ISSUE THREAD

**Issue by rikutiira** [calmm-js/kefir.atom#10]
Seems like there's some issue with Kefir's `.toPromise()` when working with atoms, as the returned promise is always `pending`.

`U.atom('foo').toPromise() // pending`
`U.atom('foo').toProperty().toPromise() // pending`
`U.atom('foo').toProperty(() => 'bar').toPromise() // pending`

**Comment by polytypic** [comment]
Hmm... I think that works as expected.   From Kefir's docs on [`toPromise`](https://kefirjs.github.io/kefir/#to-promise):

> The promise will be fulfilled or rejected at the moment source observable ends, with the latest value or error.

Atoms usually do not end.

**Comment by polytypic** [comment]
Would `U.atom('foo').take(1).toPromise()` work in your use case?

**Comment by rikutiira** [comment]
Yeah, you are right, I remembered that it would take the current value of observable. Should have checked Kefir docs for clarity, sorry!
